apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mwapp
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mwapp
  template:
    metadata:
      labels:
        app: mwapp
    spec:
      containers:
       - name: mwappc
         image: dockergeethaacc/maven-web-app:3
         ports:
         - name: tomcat
           containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mwappsvc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: mwapp
  ports:
  - port: 80
    targetPort: tomcat
